// src/components/container_components/AppWindow.vue
<script setup>
import ExpressionStatement from '../flow_objects/ExpressionStatement.vue';
import IfStatement from '../flow_objects/IfStatement.vue';
import { dropNewObjectHandler } from '../../drag_and_drop_handlers.js';
import { computed } from 'vue';
import { useStore } from 'vuex';

const store = useStore();
const main = computed(() => store.state.ast.main);

/**
 * @param {DragEvent} event
 */
function dragOverHandler(event) {
    // do stuff like change the cursor
}

const insertDrop = dropNewObjectHandler({ location: `body.${main.value.body.length}`});
</script>

<template>
    <div @dragover.prevent="dragOverHandler" @drop.stop.prevent="insertDrop" class="app-window-wrapper">
        <template v-for="(flowObject, indx) of main.body" :key="indx">
            <component :is="flowObject.type" v-bind="flowObject" :accessor="indx.toString()" :parent-ref="main.body"></component>
        </template>
    </div>
</template>

<script>
export default {
    components: {
        ExpressionStatement,
        IfStatement
    }
};
</script>

<style scoped>
.app-window-wrapper {
    flex: 1;
    overflow: auto;
    background: #efefef;
}
</style>

// src/components/container_components/AppWindow.svelte
<script>
    import ExpressionStatement from '../flow_objects/ExpressionStatement.svelte';
    import IfStatement from '../flow_objects/IfStatement.svelte';
    import { dropInsertAstCreation } from '../../drag_and_drop_handlers.js';
    import ast from '../../store/stores.js';
    
    const constructors = {
        "ExpressionStatement": ExpressionStatement,
        "IfStatement": IfStatement
    };
    
    /**
     * @param {DragEvent} event
     */
    function dragOverHandler(event) {
        // do stuff like change the cursor
    }

    $: bodyLength = $ast.main.body.length;
    
    const appendDrop = (event) => {
        const data = dropInsertAstCreation(event);

        $ast.main.body = [...$ast.main.body, data];
    }
</script>
    
<div on:dragover|preventDefault={dragOverHandler} on:drop|stopPropagation|preventDefault={appendDrop} class="app-window-wrapper">
    {#each $ast.main.body as flowObject, i (i)}
        <svelte:component this={constructors[flowObject.type]} bind:parentRef={$ast.main.body} accessor={i} />
    {/each}
</div>
    
<style>
    .app-window-wrapper {
        flex: 1;
        overflow: auto;
        background: #efefef;
    }
</style>
