// src/components/flow_objects/CallExpression.vue
<script setup>
import commonProps from '../../common_ast_props';
import MemberExpression from './MemberExpression.vue';
import Identifier from './Identifier.vue';
import StringLiteral from './StringLiteral.vue';
import UtilityDefinitions from '../../utility_definitions.js';
import { useStore } from 'vuex';
import { computed, onUpdated } from 'vue';

const props = defineProps({
    ...commonProps,
    callee: Object,
    arguments: Array
});

const parent = computed(() => props.parentRef);
const currentRef = computed(() => parent.value[props.accessor]);

let defArgNumber = () => UtilityDefinitions[currentRef.value.callee.object.name][currentRef.value.callee.property.name].args;

let isEmptyCall = () => {
    if (props.callee.type == "MemberExpression") {
        if (props.arguments.length == 0) {
            return true;
        }
    }
    return false;
};

const store = useStore();
const onMethodChange = (payloadObj) => {
    // TODO: commit change to the store using the parentRef from here
    store.commit('changeMethod', { refObj: parent.value, accessor: props.accessor, ...payloadObj });
};

//onUpdated(() => console.log(`updated ${defArgNumber()} ${currentRef.value.callee.property.name}`));
</script>

<template>
    <p style="padding-left: 10px">
        <span>
            <component @change-method="onMethodChange" is-callee :accessor="'callee'" :parent-ref="parent[accessor]" :is="callee.type" v-bind="callee"></component>
            (
                <div class="arg-box" v-if="!isEmptyCall()" v-for="(argument, i) of arguments">
                    <component :accessor="i.toString()" :parent-ref="arguments" :is="argument.type" v-bind="argument" is-argument></component>
                </div>
                <div class="arg-box" v-if="isEmptyCall()" v-for="i in defArgNumber()" >
                    <StringLiteral :accessor="i.toString()" :parent-ref="arguments" :type="'StringLiteral'" :value="''" is-argument />
                </div>
            )
        </span>
    </p>
</template>

<script>
export default {
    name: "CallExpression",
    components: {
        MemberExpression,
        Identifier,
        StringLiteral
    }
};
</script>

<style scoped>
.arg-box {
    margin-left: 10px;
    padding: 2px;
    border: 1px solid black;
}
</style>

// src/components/flow_objects/CallExpression.svelte
<script>
    import MemberExpression from './MemberExpression.svelte';
    import Identifier from './Identifier.svelte';
    import StringLiteral from './StringLiteral.svelte';
    import UtilityDefinitions from '../../utility_definitions.js';

    export let parentRef;
    export let accessor;

    //console.log(callee);

    const constructors = {
        "MemberExpression": MemberExpression,
        "Identifier": Identifier,
        "StringLiteral": StringLiteral
    };

    let self = parentRef[accessor];
    
    let defArgNumber = () => UtilityDefinitions[self.callee.object.name][self.callee.property.name].args;
    
    //const store = useStore();
    const onMethodChange = (payloadObj) => {
        // TODO: commit change to the store using the parentRef from here
        //store.commit('changeMethod', { refObj: parent.value, accessor: props.accessor, ...payloadObj });
    };
    
    //onUpdated(() => console.log(`updated ${defArgNumber()} ${currentRef.value.callee.property.name}`));
</script>


<p style="padding-left: 10px">
    <span>
        <svelte:component isCallee={true} accessor={"callee"} bind:parentRef={self} this={constructors[self.callee.type]} />
        (
            {#each self.arguments as argument, i (i)}
                <div class="arg-box">
                    {#if argument.type === "CallExpression"}
                        <svelte:self accessor={i} bind:parentRef={self.arguments} />
                    {:else}
                        <svelte:component this={constructors[argument.type]} accessor={i} bind:parentRef={self.arguments} isArgument={true} />
                    {/if}
                </div>
            {:else}
                {#each defArgNumber() as i}
                    <div class="arg-box">
                        <StringLiteral accessor={i} bind:parentRef={self.arguments} value={""} isArgument={true} />
                    </div>
                {/each}
            {/each}
        )
    </span>
</p>

    
<style>
    .arg-box {
        margin-left: 10px;
        padding: 2px;
        border: 1px solid black;
    }
</style>
