// src/components/flow_objects/ExpressionStatement.svelte
<script>
    import CallExpression from './CallExpression.svelte';
    import UtilityCallExpression from './UtilityCallExpression.svelte';
    import { dropModifyObjectHandler } from '../../drag_and_drop_handlers.js';
    import dropDataTemplates from '../../drop_data_templates';
    
    export let accessor;
    export let parentRef;

    const constructors = {
        "CallExpression": CallExpression,
        "UtilityCallExpression": UtilityCallExpression
    };

    $: self = parentRef[accessor];
    let isOverInsertSpot = false;
    
    function dragOverHandler(event) {
        // do something like change cursor
        //event.stopPropagation();
    }
    
    function insertDragOverHandler(event) {
        // something
    }
    function insertDragEnter(event) {
        isOverInsertSpot = true;
    }
    function insertDragLeave(event) {
        isOverInsertSpot = false;
    }
    function removeInsertHover(event) {
        isOverInsertSpot = false;
    }
    
    /**
     * @param {DragEvent} event
     */
    function insertDrop(event) {
        const dragData = JSON.parse(event.dataTransfer.getData('text/json'));

        let expression = dropDataTemplates.expressionStatement();
        if (dragData.type !== "expressionStatement") {
            expression.expression = dropDataTemplates.stringUtil();
        }

        parentRef.splice(accessor + 1, 0, expression);
        
        parentRef = [...parentRef];
    }
</script>

    
<div on:dragover|preventDefault={dragOverHandler} on:drop|stopPropagation|preventDefault={dropModifyObjectHandler} class="expression-container">
    {#if self.expression !== null}
        <svelte:component this={constructors[self.expression.type]} accessor={"expression"} bind:parentRef={parentRef[accessor]} />
    {:else}
        <p class="dull-text">Drag an action here</p>
    {/if}
</div>
<div
    on:dragover|preventDefault={insertDragOverHandler}
    on:dragenter|preventDefault={insertDragEnter}
    on:dragleave|preventDefault={insertDragLeave}
    on:drop|stopPropagation|preventDefault={insertDrop}
    on:drop|stopPropagation|preventDefault={removeInsertHover}
    class="line-down-box"
    class:insert-drag-over={isOverInsertSpot}>
</div>

    
<style>
    .expression-container {
        padding: 35px;
        border: 1px dashed black;
    }
    
    .line-down-box {
        margin-left: 20px;
        border-left: 1px dashed black;
        height: 30px;
        /* transition: height 0.5s ease-out; */
    }
    
    .insert-drag-over {
        border-left: 2px dashed green;
        transition: height 0.3s ease-out;
        height: 45px;
    }
</style>

// src/components/flow_objects/ExpressionStatement.vue
<script setup>
import CallExpression from './CallExpression.vue';
import commonProps from '../../common_ast_props.js';
//import dropDataTemplates from '../../drop_data_templates.js';
import { dropModifyObjectHandler, dropInsertHandler } from '../../drag_and_drop_handlers.js';
import { ref } from 'vue';

const props = defineProps({
    ...commonProps,
    expression: Object
});

let isOverInsertSpot = ref(false);

function dragOverHandler(event) {
    // do something like change cursor
    //event.stopPropagation();
}

function insertDragOverHandler(event) {
    // something
}
function insertDragEnter(event) {
    isOverInsertSpot.value = true;
}
function insertDragLeave(event) {
    isOverInsertSpot.value = false;
}
function removeInsertHover(event) {
    isOverInsertSpot.value = false;
}

const modifyDrop = dropModifyObjectHandler({ location: `${props.location}.expression` });
const insertDrop = dropInsertHandler({ refObj: props.parentRef, accessor: props.accessor });
</script>

<template>
    <div @dragover.prevent="dragOverHandler" @drop.stop.prevent="modifyDrop" class="expression-container">
        <component v-if="expression != null" :is="expression.type" v-bind="expression" :accessor="'expression'" :parent-ref="parentRef[accessor]"></component>
        <p class="dull-text" v-if="expression == null">Drag an action here</p>
    </div>
    <div
        @dragover.prevent="insertDragOverHandler"
        @dragenter.prevent="insertDragEnter"
        @dragleave.prevent="insertDragLeave"
        @drop.stop.prevent="insertDrop($event), removeInsertHover($event)"
        class="line-down-box"
        :class="{ 'insert-drag-over': isOverInsertSpot }">
    </div>
</template>

<script>
export default {
    components: {
        CallExpression
    }
};
</script>

<style scoped>
.expression-container {
    padding: 35px;
    border: 1px dashed black;
}

.line-down-box {
    margin-left: 20px;
    border-left: 1px dashed black;
    height: 30px;
    /* transition: height 0.5s ease-out; */
}

.insert-drag-over {
    border-left: 2px dashed green;
    transition: height 0.3s ease-out;
    height: 45px;
}
</style>
