// src/components/flow_objects/Identifier.svelte
<script>
    import { createEventDispatcher } from 'svelte'

    export let parentRef;
    export let accessor;
    export let isObject = false;
    export let isCallee = false;
    export let isCalleeProperty = false;

    let self = parentRef[accessor];

    let dispatch = createEventDispatcher();
    
    const onPropertyChange = (event) => {
        dispatch('changeMethod', {
            methodName: event.target.value
        });
    };
</script>
    
{#if !isCalleeProperty}
    <span>{self.name}</span>
{:else}
    <select on:change={onPropertyChange}>
        {#each Object.getOwnPropertyNames(String.prototype) as method}
            <option value={method} selected={method === self.name}>{method}</option>
        {/each}
    </select>
{/if}

// src/components/flow_objects/Identifier.vue
<script setup>
import { useStore } from 'vuex';
import commonProps from '../../common_ast_props.js';

const props = defineProps({
    ...commonProps,
    name: String,
    isObject: {
        type: Boolean,
        required: false,
        default: false
    },
    isCalleeProperty: {
        type: Boolean,
        required: false,
        default: false
    }
});

const emit = defineEmits([
    'changeMethod'
]);

const onPropertyChange = (event) => {
    emit('changeMethod', { methodName: event.target.value });
};
</script>

<template>
    <span v-if="!isCalleeProperty">{{ name }}</span>
    <select v-else @change="onPropertyChange">
        <option v-for="method of Object.getOwnPropertyNames(String.prototype)" :value="method" :selected="method == name">{{ method }}</option>
    </select>
</template>
