// src/components/flow_objects/MemberExpression.vue
<script setup>
import commonProps from '../../common_ast_props';
import Identifier from './Identifier.vue';

const props = defineProps({
    ...commonProps,
    object: Object,
    property: Object,
    isCallee: {
        type: Boolean,
        required: false,
        default: false
    }
});
</script>

<template>
    <span><component :accessor="'object'" :parent-ref="parentRef[accessor]" :is="object.type" v-bind="object" :is-object="true"></component>.<component :accessor="'property'" :parent-ref="parentRef[accessor]" :is="property.type" v-bind="property" :is-callee-property="isCallee"></component></span>
</template>

<script>
export default {
    components: {
        Identifier
    }
}
</script>

// src/components/flow_objects/MemberExpression.svelte
<script>
    import Identifier from './Identifier.svelte';

    export let parentRef;
    export let accessor;
    export let isCallee = false;

    let self = parentRef[accessor];
</script>
    
<span>
    <svelte:component
        accessor={"object"}
        bind:parentRef={self}
        this={Identifier}
        isObject={true} />
    .
    <svelte:component
        on:changeMethod
        accessor={"property"}
        bind:parentRef={self}
        this={Identifier}
        isCalleeProperty={isCallee} />
</span>
