// src/components/container_components/side_nav/FlowObjectSource.vue
<script setup>
import { dragStartHandler } from '../../../drag_and_drop_handlers.js';

const props = defineProps({
    dragData: Object
});

const dragStart = dragStartHandler(props.dragData);
</script>

<template>
    <div class="side-nav-tile" draggable="true" @dragstart="dragStart">
        <p><slot></slot></p>
    </div>
</template>

// src/components/container_components/side_nav/FlowObjectSource.svelte
<script>
    import { dragStartHandler } from '../../../lib/js/drag_and_drop/drag_and_drop_handlers.js';
    
    export let dragData;
    
    const dragStart = dragStartHandler(dragData);
</script>
    
<div class="side-nav-tile" draggable="true" on:dragstart={dragStart}>
    <p><slot></slot></p>
</div>
