// src/components/container_components/side_nav/SideNav.vue
<script setup>
import FlowObjectSource from './FlowObjectSource.vue';
import UtilityObject from '../../utilities/UtilityObject.vue';

const doActionData = {
    type: "expressionStatement"
};

const stringUtilData = {
    type: "stringUtil"
}
</script>
<template>
    <div class="side-nav-wrapper">
        <div class="project-structure-pane">
            <FlowObjectSource :dragData="doActionData">Drag Me Tester</FlowObjectSource>
        </div>

        <div class="utility-pane">
            <UtilityObject :dragData="stringUtilData">String Util</UtilityObject>
        </div>
    </div>
    
</template>

<style scoped>
.side-nav-wrapper {
    width: 33%;
    max-width: 500px;
    height: 100%;
    background: #ddd;
    display: flex;
    flex-direction: column;
}

.project-structure-pane {
    flex: 1;
}

.utility-pane {
    min-height: 200px;
    overflow: auto;
    border-top: 2px solid #888;
}
</style>

// src/components/container_components/side_nav/SideNav.svelte
<script>
    import FlowObjectSource from './FlowObjectSource.svelte';
    
    const doActionData = {
        type: "expressionStatement"
    };
    
    const stringUtilData = {
        type: "stringUtil"
    }
</script>

<div class="side-nav-wrapper">
    <div class="project-structure-pane">
        <FlowObjectSource dragData={doActionData}>Drag Me Tester</FlowObjectSource>
    </div>

    <div class="utility-pane">
        <FlowObjectSource dragData={stringUtilData}>String Util</FlowObjectSource>
    </div>
</div>
    
<style>
    .side-nav-wrapper {
        width: 33%;
        max-width: 500px;
        height: 100%;
        background: #ddd;
        display: flex;
        flex-direction: column;
    }
    
    .project-structure-pane {
        flex: 1;
    }
    
    .utility-pane {
        min-height: 200px;
        overflow: auto;
        border-top: 2px solid #888;
    }
</style>
